### ISSUE TITLE
HLSL -> GLSL : Incorrect variable declarations when using for loop

### ISSUE THREAD

**Issue by Loki7979** [KhronosGroup/SPIRV-Cross#346] opened 2017-11-27 02:43 UTC
Hi,

I have coded this simple HLSL skinning vertex shader:

```
cbuffer _shared_camera
{
	row_major matrix V;
	row_major matrix invV;
    row_major matrix P;
	row_major matrix invP;
	float zNear;
	float zFar;
};
#define MAX_JOINTS 128
cbuffer skinningCB
{
    row_major matrix boneMatrices[MAX_JOINTS];
};

struct VertexIn
{
	float3 position : POSITION;
	float2 uv1 : TEXCOORD0;
	uint4 boneIndices : BLENDINDICES;
	float4 boneWeights : BLENDWEIGHT;
	uint instanceID : SV_InstanceID;
};
struct VertexOut
{
	float4 pos : SV_POSITION;
	float2 tex : TEXCOORD0;
	float3 posWorld : TEXCOORD1;
	float3 posView : TEXCOORD2;
};

//--------------------------------------------------------------------------------------
// VERTEX_SHADER vs_main
//--------------------------------------------------------------------------------------

VertexOut vs_main(VertexIn input)
{
	VertexOut output;
	
	output.posWorld = float3(0,0,0);
	
	for(int i = 0; i < 4; i++)
	{
		uint boneIndex = input.boneIndices[i];
		
		if(boneIndex < MAX_JOINTS)
		{
			float boneWeight = input.boneWeights[i];
			row_major matrix boneMatrix = boneMatrices[boneIndex];
			output.posWorld += mul(float4(input.position, 1), boneMatrix) * boneWeight;
		}
	}
		
	output.posView = mul(float4(output.posWorld, 1), V).xyz;
	output.pos = mul(float4(output.posView,1), P);
	output.tex = input.uv1;
	return output;
}	
```

I have translated the shader to SPIR-V without issues using glslang, but when I try to translate to GLSL using SPIRV-Cross and compile the shader on Windows platform I get the following error message:

0(63) : error C1060: incompatible types in initialization
0(63) : error C1056: invalid initialization
0(63) : error C1020: invalid operands to "<"
0(63) : error C1022: operands to "++" must be numeric

The obtained GLSL code is the following:

```
#version 420

struct VertexIn
{
    vec3 position;
    vec2 uv1;
    uvec4 boneIndices;
    vec4 boneWeights;
    uint instanceID;
};

struct VertexOut
{
    vec4 pos;
    vec2 tex;
    vec3 posWorld;
    vec3 posView;
};

layout(std140) uniform skinningCB
{
    mat4 boneMatrices[128];
} _skinningCB;

layout(std140) uniform _shared_camera
{
    mat4 V;
    mat4 invV;
    mat4 P;
    mat4 invP;
    float zNear;
    float zFar;
} __shared_camera;

layout(location = 0) in vec3 input_position;
layout(location = 1) in vec2 input_uv1;
layout(location = 2) in uvec4 input_boneIndices;
layout(location = 3) in vec4 input_boneWeights;
uniform int SPIRV_Cross_BaseInstance;
layout(location = 0) out vec2 _entryPointOutput_tex;
layout(location = 1) out vec3 _entryPointOutput_posWorld;
layout(location = 2) out vec3 _entryPointOutput_posView;

VertexIn _267;
VertexOut _268;

void main()
{
    VertexIn _234 = _267;
    _234.position = input_position;
    VertexIn _236 = _234;
    _236.uv1 = input_uv1;
    VertexIn _238 = _236;
    _238.boneIndices = input_boneIndices;
    VertexIn _240 = _238;
    _240.boneWeights = input_boneWeights;
    VertexIn _242 = _240;
    _242.instanceID = (gl_InstanceID + SPIRV_Cross_BaseInstance);
    VertexIn param = _242;
    VertexOut _244 = _268;
    _244.posWorld = vec3(0.0);
    VertexOut _271;
    for (VertexOut _269 = _244, _270 = 0; _270 < 4; _269 = _271, _270++)
    {
        uint _177 = param.boneIndices[_270];
        if (_177 < 128u)
        {
            VertexOut _248 = _269;
            _248.posWorld = _269.posWorld + vec3(((_skinningCB.boneMatrices[_177] * vec4(param.position, 1.0)) * param.boneWeights[_270]).xyz);
            _271 = _248;
        }
        else
        {
            _271 = _269;
        }
    }
    vec3 _217 = (__shared_camera.V * vec4(_269.posWorld, 1.0)).xyz;
    VertexOut _252 = _269;
    _252.posView = _217;
    vec4 _227 = __shared_camera.P * vec4(_217, 1.0);
    VertexOut _256 = _252;
    _256.pos = _227;
    VertexOut _258 = _256;
    _258.tex = param.uv1;
    gl_Position = _227;
    _entryPointOutput_tex = param.uv1;
    _entryPointOutput_posWorld = _258.posWorld;
    _entryPointOutput_posView = _217;
}
```
If you take a look into this code line:

for (VertexOut _269 = _244, _270 = 0; _270 < 4; _269 = _271, _270++)

You can see that the variable _270 has not been declared as it should be int _270 = 0

Please, could you take a look into this issue?
Thank you very much

**Comment by HansKristian-ARM** [comment] 2017-11-27 10:16
Did you try this with the latest master? This issue should be fixed there as I fixed several very similar looking bugs just a few days ago.

**Comment by Loki7979** [comment] 2017-11-30 05:17
Sorry for my late response.

I was working with a very recent master version. Just pulled from the master branch and this issue is not showing up anymore. Thanks!

Unfortunatelly I still I am getting errors of the same type in other shaders. For example, take a look a this HLSL code (this is just a part form a big shader):

```
int GetCascade(float3 fragWorldPosition)
{
	[unroll]
	for(uint cascadeIndex = 0; cascadeIndex < shadowCascadesNum; cascadeIndex++)
	{
		matrix worldToShadowMap = mul(lightVP[cascadeIndex], GetClip2TexMatrix());
		float4 fragShadowMapPos = mul(float4(fragWorldPosition, 1), worldToShadowMap);
		
		if(fragShadowMapPos.z >= 0 && fragShadowMapPos.z <= 1 &&
		max(fragShadowMapPos.x, fragShadowMapPos.y) <= 1 && 
		min(fragShadowMapPos.x, fragShadowMapPos.y) >= 0) 
			return cascadeIndex;
	}
	return -1;
}
```

SPIRV-Cross (latest master) generates the following GLSL code:

```
int GetCascade(vec3 fragWorldPosition)
{
    uint _144;
    uint _462;
    mat4 _398;
    mat4 _401;
    for (uint _4267 = 0u; _4267 < __shared_shadows.shadowCascadesNum; _462 = (uint _4272) + uint(1), _4267 = _462)
    {
        mat4 _4273;
        do
        {
            if (__shared_renderSettings.invertVCoord == 1u)
            {
                _4272 = _4267;
                _4273 = mat4(vec4(0.5, 0.0, 0.0, 0.0), vec4(0.0, -0.5, 0.0, 0.0), vec4(0.0, 0.0, 1.0, 0.0), vec4(0.5, 0.5, 0.0, 1.0));
                break;
            }
            _4272 = _4267;
            _4273 = mat4(vec4(0.5, 0.0, 0.0, 0.0), vec4(0.0, 0.5, 0.0, 0.0), vec4(0.0, 0.0, 1.0, 0.0), vec4(0.5, 0.5, 0.0, 1.0));
            break;
        } while (false);
        vec4 _434 = (_4273 * __shared_lighting.lightVP[_4272]) * vec4(fragWorldPosition, 1.0);
        if ((((_434.z >= 0.0) && (_434.z <= 1.0)) && (max(_434.x, _434.y) <= 1.0)) && (min(_434.x, _434.y) >= 0.0))
        {
            return int(_4272);
        }
    }
    return -1;
}

```

The compiler reports the following error:

0(119) : error C0000: syntax error, unexpected identifier, expecting '(' or ')' at token "_4272"
0(128) : error C0000: syntax error, unexpected reserved word "break", expecting ')' at token "break"
0(132) : error C0000: syntax error, unexpected reserved word "break", expecting ')' at token "break"

It seems it doesn´t like this line of code

 for (uint _4267 = 0u; _4267 < __shared_shadows.shadowCascadesNum; _462 = (uint _4272) + uint(1), _4267 = _462)

I believe is complaining about _4272 declaration 

If fact now I am getting errors almost in every HLSL shader SPIRV-Cross translates to GLSL.
If you want to see the whole shader let me know.

Thank you!

**Comment by HansKristian-ARM** [comment] 2017-11-30 13:12
Ye ... I've seen similar cases and fixed them, guess I missed some cases.
Unfortunately, disassembling optimized SPIR-V from HLSL is very hard-mode. :( Looks like I have more bug-fixing to do.

**Comment by Loki7979** [comment] 2017-12-01 04:32
It's curious because using an old version of SPIRV-Cross the HLSL -> GLSL translation was working almost perfectly, and when I decided to pull from the master everything screwed up.

It seems you have done some important changes on the core logic lately (in the last months). Moreover, now the resulting GLSL code structure is much more different than the one from the original HLSL code. 

I believe I am sticking to the old version for now. I need the translation HLSL -> GLSL to work.
I will continue posting other issues in order to help fixing all the bugs.

Thank you!

**Comment by HansKristian-ARM** [comment] 2017-12-05 15:15
Reproduced.

**Closed** 2017-12-06 08:49 UTC
Labels: bug
