### ISSUE TITLE
Shader reflection is returning incorrect byte size on float arrays 

### ISSUE THREAD

**Issue by Loki7979** [KhronosGroup/SPIRV-Cross#193] opened 2017-05-31 13:38 UTC
Hi,

I have this constant buffer (or uniform block) on fragment shader (HLSL):

```
cbuffer _shared_shadows
{
	float shadowCascadesSplits[4];
};
```

Once I generate the SPIRV binary using glslang, I get all the constant buffers information using the reflection feature provided by SPIRV-Cross:

```
ShaderTranslator::ReflectionInfo ShaderTranslator::GetReflectionInfo(const std::vector<uint32_t>& spirv_binary)
{
	ReflectionInfo info;
	
	spirv_cross::Compiler comp(spirv_binary);

	spirv_cross::ShaderResources activeResources = comp.get_shader_resources(comp.get_active_interface_variables());

	for (auto &u : activeResources.uniform_buffers)
	{
		UniformBlockInfo ubInfo;
		ubInfo.name = u.name;

		spirv_cross::SPIRType varType = comp.get_type_from_variable(u.id);

		ubInfo.binding = comp.get_decoration(u.id, spv::DecorationBinding);
		ubInfo.byteSize = comp.get_declared_struct_size(varType);

		for (uint32_t memberIndex = 0; memberIndex < varType.member_types.size(); ++memberIndex)
		{
			UniformInfo uInfo;

			uInfo.name = comp.get_member_name(u.base_type_id, memberIndex);
			uInfo.byteSize = comp.get_declared_struct_member_size(varType, memberIndex);
			uInfo.offset = comp.get_member_decoration(u.base_type_id, memberIndex, spv::Decoration::DecorationOffset);
			uInfo.location = comp.get_member_decoration(u.base_type_id, memberIndex, spv::Decoration::DecorationLocation);

			ubInfo.uniforms.push_back(uInfo);
		}
		info.uniformBlocks.push_back(ubInfo);
	}
	return info;
}
```

The following code line of the code exposed returns the byte size of each constant buffer member 
`
uInfo.byteSize = comp.get_declared_struct_member_size(varType, memberIndex);`

It works well on every member of all constant buffers I have on my shaders, except when asking for a float array byte size.

In case of member float shadowCascadesSplits[4]; should return 16 but returns 64 bytes.

Could you help me with this? Thanks in advance

**Comment by HansKristian-ARM** [comment] 2017-05-31 14:27
This is fixed in std430, but not sure how that maps to HLSL, anyways, closing as not a bug.

**Closed by HansKristian-ARM** 2017-05-31 14:27 UTC

**Comment by Loki7979** [comment] 2017-05-31 15:02
Finally I solved the wasted memory problem by using a different type of container available on HLSL:

cbuffer _shared_shadows
{
	vector<float, 6> shadowCascadesSplits;
};

This time only 4 bytes are assigned to every container element. Hope this helps somebody!
