### ISSUE TITLE
Question: GL_ARB_separate_shader_objects not defining gl_PerVertex or gl_PerFragment

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#185] opened 2017-05-17 13:09 UTC
I have a question regarding the extension GL_ARB_separate_shader_objects. When I set it to require, the spec says I need to redefine gl_PerVertex and gl_PerFragment with all used built-ins, so effectively I need something like 

```
struct gl_PerVertex
{
    vec4 gl_Position;
};
```

However enabling this extension doesn't redeclare it as per the spec. I've searched the SPIRV-Cross source code and there is no mention of it. Is there a reason why they aren't or shouldn't be?

**Comment by HansKristian-ARM** [comment] 2017-05-17 14:23
This is indeed not implemented. I suppose we could add an option to enable SSO support. A simple option to emit SSO compatible shaders should be fairly easy.

**Comment by redorav** [comment] 2017-05-17 15:25
That's awesome, thank you

**Comment by HansKristian-ARM** [comment] 2017-05-22 14:01
PR: https://github.com/KhronosGroup/SPIRV-Cross/pull/188

**Comment by HansKristian-ARM** [comment] 2017-05-30 09:02
@redorav, any feedback? If not, I will merge as is.

**Comment by redorav** [comment] 2017-05-30 09:05
@HansKristian-ARM My apologies, the task that depends on this has been delayed for a few days due to deadlines and I was hoping to get back to you sooner. I'm happy with it being merged as is and giving feedback later on.

**Comment by HansKristian-ARM** [comment] 2017-05-30 09:08
ok, np. I will merge shortly then.

**Comment by HansKristian-ARM** [comment] 2017-05-31 08:08
Merged. Feel free to reopen if there are issues or missing functionality.

**Closed by HansKristian-ARM** 2017-05-31 08:08 UTC
Labels: enhancement

**Comment by redorav** [comment] 2017-11-17 11:47
Hi @HansKristian-ARM I've been able to finally test this. I've tried it by adding a require_extension("GL_ARB_separate_shader_objects") and also enabling the separate_shader_objects = true in the options.

However, the block isn't being redeclared. I've looked at the source and the emit_declared_builtin_block function never gets to the part where it actually emits the builtin block. Am I doing something wrong?

**Comment by HansKristian-ARM** [comment] 2017-11-17 12:02
Works for me if I use --separate-shader-objects on CLI though ...

**Comment by redorav** [comment] 2017-11-17 12:08
I've sent you the shader I'm using to your email. Does it work for you with it? What GL version are you targeting? I'm trying to target 430.

**Comment by HansKristian-ARM** [comment] 2017-11-17 12:09
Reproduced. It seems like HLSL outputs position in a different way, weird ... I'll try to fix this.

**Comment by redorav** [comment] 2017-11-17 12:09
Awesome, thanks a lot!

**Comment by HansKristian-ARM** [comment] 2017-11-17 12:37
PR: https://github.com/KhronosGroup/SPIRV-Cross/pull/327

**Comment by redorav** [comment] 2017-11-17 12:38
Great, I'll test as soon as it goes through
