### ISSUE TITLE
spirv-cross yields invalid GLSL (array index out of range)

### ISSUE THREAD

**Issue by afd** [KhronosGroup/SPIRV-Cross#1124] opened 2019-08-22 15:17 UTC
[Files to repro the problem](https://github.com/KhronosGroup/SPIRV-Cross/files/3530777/tofile.zip)

Doing:

```
spirv-cross generated_0.opt.spv --output temp.frag && glslangValidator temp.frag
```

gives:

```
ERROR: 0:2870: '[' :  array index out of range '1987837952'
ERROR: 0:2870: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
```

Found via [GraphicsFuzz](https://github.com/google/graphicsfuzz) on spirv-cross git commit 4ce04480.

**Comment by HansKristian-Work** [comment] 2019-08-27 14:13
The SPIR-V is intentionally accessing the array out of bounds here and the codegen is "correct", so I think should be rejected by spirv-val, but it's not. Not sure if this should be classified as a SPIRV-Cross bug.

**Comment by HansKristian-Work** [comment] 2019-09-05 08:35
Closing as not a bug.

**Closed by HansKristian-Work** 2019-09-05 08:35 UTC
Labels: not a bug
