### ISSUE TITLE
MSL that writes to SampleMask fails to compile

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/SPIRV-Cross#443] opened 2018-02-09 17:18 UTC
See attached SPIR-V.  Repro:

```
./spirv-cross sample_mask.spv --msl --output sample_mask.msl
xcrun --sdk macosx10.13 metal -x metal -std=osx-metal1.2 -Werror -Wno-unused-variable sample_mask.msl
```

Generates the following errors:
```
sample_mask.msl:165:26: error: type 'uint [1]' is not valid for attribute 'sample_mask'
    uint gl_SampleMask [[sample_mask]][1];
                         ^~~~~~~~~~~
sample_mask.msl:665:5: error: use of undeclared identifier 'gl_SampleMask'
    gl_SampleMask[0] = _265;
    ^
2 errors generated.
```
[sample_mask.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1711844/sample_mask.zip)

**Comment by billhollings** [comment] 2018-02-10 17:15
I'm looking into this.

**Comment by billhollings** [comment] 2018-02-10 17:35
@danginsburg 

`sample_mask.zip` seems to only include the MSL. Do you have the SPIR-V?

**Comment by danginsburg** [comment] 2018-02-12 14:32
My mistake, SPIR-V in the attached file.

[sample_mask_spv.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1716585/sample_mask_spv.zip)

**Comment by HansKristian-ARM** [comment] 2018-02-14 08:24
Overall I think it's going to be near impossible to make sure -Wsometimes-uninitialized never triggers with optimized SPIR-V. Is it possible to disable that warning from within the source?

**Comment by billhollings** [comment] 2018-02-14 15:35
I've confirmed that the warning/error is successfully removed by adding the following pragma line to the MSL...

		#pragma clang diagnostic ignored "-Wsometimes-uninitialized"

However...turning this off for all shaders, regardless of how well-formed they are, feels intrusive and ugly (not to mention will cause every single MSL test reference shader to change).

Could we use one of the following two approaches?

1. Couldn't this be fixed by ensuring that that all MSL declarations are initialized to their default values if not set to something else explicitly? If so...where would be the most appropriate place to handle that?

2. If not...is there a reasonable way to detect when to add the pragma (ie- only when the warning will be triggered by an uninitialized variable), rather than adding it to all MSL shaders?

**Comment by HansKristian-ARM** [comment] 2018-02-14 15:40
Both are viable. 1. is probably the easiest option as we could just tack on `= {}` any variable/temporary declaration which does not contain an initializer. I do fear this can pessimize performance in some cases though, but we kinda do that for OpUndef already in MSL.

**Comment by billhollings** [comment] 2018-02-14 16:52
@danginsburg @HansKristian-ARM 

In C++ (which MSL is based on), local variables are not automatically initialized...which by definition will result in undefined behaviour if the code executes a path on which the variable remains uninitialized.

So...is it fundamentally a mistake for MSL to do what this shader is doing...which is not initialize on all paths? Or would the shader author understand that only initialized paths will be followed (hence the "sometimes" nature of the warning).

If we do want to initialize...where to do it? `variable_decl()` is called all over the place. Are we just concerned about temps and locals? Where best to handle them?

If we don't want to initialize always because we don't want to take a performance hit on initializing unnecessarily...AND we are confident that the shader is well written even when it does partial initializations...then I think the best path forward is to remove the use of `-Werror` in Dan's command above...and let the warning happen without failing the shader compile. 

When compiling at runtime, MoltenVK does not enable `-Werror`...and it is common to see the warnings logged at runtime by MoltenVK when Debug mode is active. This will just be an additional warning that will get logged.

`test_shaders.py` uses  `-Werror`...but if we encounter test shaders that have this issue...we can add `-Wno-sometimes-uninitialized` to the build settings used in `test_shaders.py` (as is done with `-Wno-unused-variable` there already).

Thoughts?

**Comment by danginsburg** [comment] 2018-02-14 17:03
I copy-pasted -Werror from test_shaders.py which is why it was in my command-line.  If it does not pose an issue with MoltenVK then it's fine with me if we leave it at that for now until we encounter a shader where this is an actual issue.

**Comment by HansKristian-ARM** [comment] 2018-02-15 09:04
Ok, so. I think we can modify the test script to have -Wno-sometimes-uninitialized, and not do anything to appease MSL's warning. I didn't realize we ran tests with -Werror, but I guess it makes sense. Consumers of the MSL can use -Wno-sometimes-uninitialized in that case if they do not want to see them. As a general rule of thumb we should try avoid emitting code with warnings, but this is case where I think a fix would be more painful than the problem it solves.

I don't think there are cases now where the original source has well defined variables on use, and the generated MSL does not. In that case, automatically assigning 0 would also be wrong anyways.

In GLSL and HLSL, variables are not initialized in case of `int foo;`, similar to MSL, except there is no zealous warning about it in most cases.

**Comment by HansKristian-ARM** [comment] 2018-02-21 13:02
As sample_mask itself it working, I'll consider this issue fixed.
Please create a new issue or PR for the uninitialized warning issue if necessary.

**Closed by HansKristian-ARM** 2018-02-21 13:02 UTC
Labels: bug
