### ISSUE TITLE
MSL: binding is not match

### ISSUE THREAD

**Issue by minggo** [KhronosGroup/SPIRV-Cross#1248] opened 2020-01-03 07:59 UTC
I used `glslangValidator` and `spirv-cross` to translate GLSL ES shader to MSL, the binding is not right, the command are:
```
glslangValidator -e main -o gles3frag.spv -V  gles3.frag
spirv-cross --msl --output gles3frag.metal ./gles3frag.spv
```

Content of `gles3.frag` is 
```
#version 310 es

 precision highp float;

layout(std140, binding=2) uniform Color
{
    vec4 u_color;
};

layout(location = 0) out vec4 o_color;

void main()
{
    o_color = u_color;
}
```

Output MSL shader is
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Color
{
    float4 u_color;
};

struct main0_out
{
    float4 o_color [[color(0)]];
};

fragment main0_out main0(constant Color& _12 [[buffer(0)]])
{
    main0_out out = {};
    out.o_color = _12.u_color;
    return out;
}
```

As you see, the binding of uniform block `Color` is changed from `2` to `0`. It seems the output MSL ignore binding information set in GLSL ES shader, just start binding from 0.

**Comment by HansKristian-Work** [comment] 2020-01-03 14:40
This is expected behavior. MSL binding space does not match SPIR-V. There is the option https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L303, or --msl-decoration-binding from CLI which will map DecorationBinding to MSL binding space. It won't work in the general case however, but for simple cases like this, it should do the trick.

**Comment by minggo** [comment] 2020-01-08 02:43
Thanks for the answer. I have a question, then how do i know the binding for a uniform block? As in this issue, how do i know the binding index of `Color` in MSL? As the shader is converted in runtime, so need to know the binding index in runtime too.

**Comment by HansKristian-Work** [comment] 2020-01-08 09:50
There are basically three approaches you can take here:
- Use --msl-decoration-binding approach. Then you know the binding based on the SPIR-V.
- Use https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L418 API to get full control of how SPIR-V bindings are mapped to MSL. Here you also know the binding.
- Use the automatic binding scheme, you can then use https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L452 API after calling ::compile() to get the binding you ended up with.

I don't recommend the last one.

**Comment by minggo** [comment] 2020-01-09 01:41
Thanks for the answer. I can not use these methods, as the shader is compiled offline, my codes can only get converted MSL. We need to change to compile GLSL ES in runtime if want to use these methods, which may slow down the runtime speed.

**Comment by HansKristian-Work** [comment] 2020-01-09 08:37
Well, if you're compiling off-line as part of a build system there is nothing stopping you from making your own wrapper which extracts the automatic binding information you need.

**Comment by floooh** [comment] 2020-01-15 13:12
Looks like we stumbled over the same problem, but when using SPIRVCross as library:

So far it seems that the CompilerMSL option ```enable_decoration_binding``` fixes the problem (at least for our use case):

https://github.com/floooh/sokol-tools/issues/29#issuecomment-574652253

**Comment by HansKristian-Work** [comment] 2020-01-15 15:38
Doesn't seem to be any further actions to take here, closing.

**Closed by HansKristian-Work** 2020-01-15 15:38 UTC
Labels: question

**Comment by wasimabbas-arm** [comment] 2024-02-01 15:04
> There are basically three approaches you can take here:
> 
> * Use --msl-decoration-binding approach. Then you know the binding based on the SPIR-V.
> * Use https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L418 API to get full control of how SPIR-V bindings are mapped to MSL. Here you also know the binding.
> * Use the automatic binding scheme, you can then use https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L452 API after calling ::compile() to get the binding you ended up with.

These were not permalinks so I don't now what they are pointing at. Was this by any chance pointing at `get_automatic_msl_resource_binding`. What was the third option?
