### ISSUE TITLE
GLSL's merge to direct for loop is regressed

### ISSUE THREAD

**Issue by loic-sharma** [KhronosGroup/SPIRV-Cross#2031] opened 2022-09-30 01:20 UTC
## Problem 
The Flutter project [has a test](https://github.com/flutter/engine/blob/main/lib/ui/fixtures/shaders/supported_op_shaders/246_OpLoopMerge.frag) that previously used this branch to generate a `for` loop:

https://github.com/KhronosGroup/SPIRV-Cross/blob/81ba8f78f6646e5635129bd738f25bb3f43bbdb9/spirv_glsl.cpp#L15586-L15596

The test now incorrectly falls back to this branch instead:

https://github.com/KhronosGroup/SPIRV-Cross/blob/81ba8f78f6646e5635129bd738f25bb3f43bbdb9/spirv_glsl.cpp#L15612-L15632

This problem reproduces on both my Windows and macOS machines. The Flutter project is currently on https://github.com/KhronosGroup/SPIRV-Cross/commit/50b4d5389b6a06f86fb63a2848e1a7da6d9755ca which is not affected by this bug.

## Cause

It seems `SPIRBlock` is incorrectly initialized here: https://github.com/KhronosGroup/SPIRV-Cross/blob/81ba8f78f6646e5635129bd738f25bb3f43bbdb9/spirv_parser.cpp#L977

https://github.com/KhronosGroup/SPIRV-Cross/blob/81ba8f78f6646e5635129bd738f25bb3f43bbdb9/spirv_cross_containers.hpp#L579

After the call to `set`, I'd expect that `current_block->ops.buffer_size` to be 0. However, it is a random non-zero value instead. It appears that any members after [`SPIRBlock.mesh`](https://github.com/KhronosGroup/SPIRV-Cross/blob/81ba8f78f6646e5635129bd738f25bb3f43bbdb9/spirv_common.hpp#L843-L848) aren't initialized. As a result, the following check causes `block_is_loop_candidate` to return `false` incorrectly:

https://github.com/KhronosGroup/SPIRV-Cross/blob/81ba8f78f6646e5635129bd738f25bb3f43bbdb9/spirv_cross.cpp#L1524-L1527

**Comment by HansKristian-Work** [comment] 2022-10-03 10:43
Are you sure this is not simply a header mismatch? Where you're compiling against older headers that did not add the mesh member? I cannot reproduce this and there are default initialization in place that clears these members to 0.

I even tried hacking in this code to verify that we're not accidentally relying on zero-initialized memory:

```
diff --git a/spirv_cross_containers.hpp b/spirv_cross_containers.hpp
index 506b069c..4271419a 100644
--- a/spirv_cross_containers.hpp
+++ b/spirv_cross_containers.hpp
@@ -208,6 +208,7 @@ public:
     {
         this->ptr = stack_storage.data();
         buffer_capacity = N;
+        memset(&stack_storage, 0xab, sizeof(stack_storage));
     }
 
     SmallVector(const T *arg_list_begin, const T *arg_list_end) SPIRV_CROSS_NOEXCEPT : SmallVector()
diff --git a/spirv_parser.cpp b/spirv_parser.cpp
index 49eb1933..cd66ba6d 100644
--- a/spirv_parser.cpp
+++ b/spirv_parser.cpp
@@ -975,6 +975,8 @@ void Parser::parse(const Instruction &instruction)
             SPIRV_CROSS_THROW("Cannot start a block before ending the current block.");
 
         current_block = &set<SPIRBlock>(id);
+        if (!current_block->ops.empty())
+            abort();
         break;
     }
```

**Comment by HansKristian-Work** [comment] 2022-10-26 09:49
Closing as not a bug unless shown otherwise.

**Closed by HansKristian-Work** 2022-10-26 09:49 UTC
Labels: not a bug
