### ISSUE TITLE
SPIRV-Cross dont work

### ISSUE THREAD

**Issue by twanks123** [KhronosGroup/SPIRV-Cross#29] opened 2016-07-08 00:40 UTC
Hello guys,
i am really sorry that i have to create a issue here, but i tryed almost everything and i have always the same problem and i dont know if its a bug or a mistake of my part.

So i want to use SPIRV-Cross do build automatically an appropriate Pipeline-Layout, but the library stops always at this part in spirv_cross.cpp in the parse() function:

`	uint32_t offset = 5;
	while (offset < len)
		inst.emplace_back(spirv, offset);`

There is always an endless loop here, with every shader i tryed to load. Shaders working fine. I tryied using a static lib (building with VS 15) and adding the files to my own codebase. With both approaches the same result.

Hope you can help me :(

**Comment by HansKristian-ARM** [comment] 2016-07-08 07:05
This looks non-sensical to me. Instruction constructor modifies offset there. Can you try logging what happens to offset in Instruction::Instruction? It sounds like a compiler bug to me, really. It works fine on all compilers I've tested (GCC, Clang, MSVC 2013).

**Comment by twanks123** [comment] 2016-07-08 15:56
Offset stops at around ~300. Shader-Code has a size of 1.388. Here is one:

#version 450

out gl_PerVertex { 
     vec4 gl_Position;
};

// Uniforms
layout (set = 0, binding = 0) uniform UBO 
{
	mat4 world;
};

layout (set = 1, binding = 0) uniform UBO2 
{
	mat4 viewProjection;
};

// In Data
layout (location = 0) in vec3 inPos;
layout (location = 1) in vec2 inUV;
layout (location = 2) in vec3 inNormal;

// Out Data
layout (location = 0) out vec2 outUV;

void main() 
{
	outUV 		= inUV;
	gl_Position = viewProjection * world * vec4(inPos.xyz, 1.0);
}

**Comment by twanks123** [comment] 2016-07-08 17:06
Yes here it is:

[vert.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/354730/vert.zip)

**Comment by HansKristian-ARM** [comment] 2016-07-08 17:17
Oddly enough, I'm getting the same output for that .spv file.
Are you or anyone else able to test it on MSVC 2013 to narrow it down?

Only explanation I have so far is a compiler issue.

**Comment by twanks123** [comment] 2016-07-08 18:28
Mhh with VC13 i am getting always an exception: spirv_cross:CompilerError at location..
I pretty new to c++ and visual studio, so i might be doing some things horrible wrong. I will remove spirv-cross from my project for now. :/ sad

**Comment by amerkoleci** [comment] 2016-07-10 10:01
Happens to me too with VS 2015, endless loop

**Comment by HansKristian-ARM** [comment] 2016-07-10 10:55
I'll try to repro on a VS 2015 install.

**Comment by HansKristian-ARM** [comment] 2016-07-11 08:11
Alright, I tried on:
Visual Studio Community 2015
Version 14.0.25421.03 Update 3, which should be the latest (downloaded today).

Tried all variants:
Debug|Relase and x86|x64.

Ran on command line:
SPIRV-Cross.exe vert.spv

vert.spv works fine on all build variants for me. Does it happen from command line as well? If it only happens by using API, I would like a reproducing sample.

**Comment by twanks123** [comment] 2016-07-11 14:51
Maybe our "load_spirv_file();" function is completely different and causes somehow this error. 

    //Read a binary file into a buffer (e.g. a SPIRV file)
    std::vector<uint32_t> readBinaryFile(const char* filename)
    {
        std::ifstream file(filename, std::ios::binary);

        if (!file.is_open())
            vkTools::exitFatal("ERROR in vkTools::readBinaryFile(): Could not load '" + std::string(filename) + "' file.");

        std::vector<char> spirv((std::istreambuf_iterator<char>(file)), (std::istreambuf_iterator<char>()));

        file.close();

        // Copy data from the char-vector to a new uint32_t-vector
        std::vector<uint32_t> spv(spirv.size());
        memcpy(spv.data(), spirv.data(), spirv.size());

        return spv;
    }

This is how i loading the spirv-file and then calling this:

spirv_cross::CompilerGLSL glsl(std::move(spirv_binary));

Could you show me your way of loading the binary spirv-file?
Btw: i couldnt figured out how to pass it directly into a std::vector<uint32_t>, so i am doing this completely unneccessary copy :O do you know how i can load it directly?

**Comment by HansKristian-ARM** [comment] 2016-07-11 15:05
Oh. This looks wrong. You're using the size of a char buffer. If you create a uint32_t buffer you get a 4 times larger buffer which has lots of zeroes in it, which is not valid SPIR-V code.

```
std::vector<uint32_t> spv(spirv.size() / sizeof(uint32_t));
memcpy(spv.data(), spirv.data(), spirv.size());
```
seems more correct.

**Comment by twanks123** [comment] 2016-07-11 15:30
That was it ._. Now it works. But do you know how to read the binary data directly into a vector of uint32_t? Thanks :dancer:

**Comment by HansKristian-ARM** [comment] 2016-07-11 15:33
I prefer C stdio for dealing with binary data like this.
This is how SPIRV-Cross does it at least:
https://github.com/KhronosGroup/SPIRV-Cross/blob/master/main.cpp#L149.
Looking at it again, it's not super strict about error handling, but oh well.

Closing this since it wasn't a SPIRV-Cross bug.

**Closed by HansKristian-ARM** 2016-07-11 15:33 UTC
