### ISSUE TITLE
MSL : nested cbuffer structs have incorrectly aligned members

### ISSUE THREAD

**Issue by fatkas** [KhronosGroup/SPIRV-Cross#466] opened 2018-02-22 16:44 UTC
basically fix for https://github.com/KhronosGroup/SPIRV-Cross/issues/457 broke packing of members of nested structs. thats a huge regression for us

**Comment by HansKristian-ARM** [comment] 2018-02-22 16:50
I'll preemptively ask for an example GLSL/SPIR-V file which triggers this issue.
Given there have been two regressions now in a row on MSL packing, I suspect a refactor/redesign is in order ...

**Comment by fatkas** [comment] 2018-02-22 16:58
for us this particular issue results in "error: size of constant buffer cannot exceed 65536" because size of the array of this nested structs was carefully chosen to fit 65536 bytes. not sure how do we test this without doing actual msl source compilation

**Comment by HansKristian-ARM** [comment] 2018-02-22 17:19
The title says HLSL, it's MSL, right?

**Comment by fatkas** [comment] 2018-02-22 17:30
its hlsl -> msl . for whatever reason i thought title should have source language

**Comment by HansKristian-ARM** [comment] 2018-02-22 17:43
Right. First step will need to be getting a small HLSL or GLSL source file which shows a clear difference before and after that commit and go from there. I can't tell from that commit why this regression would happen.

**Comment by fatkas** [comment] 2018-02-22 17:47
```
-			if (mbr_type.type_alias)
 -			{
 -				auto &mbr_type_alias = get<SPIRType>(mbr_type.type_alias);
 -				mark_as_packable(mbr_type_alias);
 -			}
```
because of that? type is not marked as packable anymore. i'll try to come up with a hlsl repro tomorrow

**Comment by HansKristian-ARM** [comment] 2018-02-22 17:49
Right, I'm just not sure why nested structs start failing (and not everything would break in half).

**Comment by billhollings** [comment] 2018-02-22 19:03
The code that @fatkas highlights was removed to fix #457. The issue there was that the SPIR-V included two sets of identical (including names) nested structs.

One set was used as an shader input and needed to be aligned correctly. The other nested struct was used as a local function only, does not include Offset decorations, and therefore cannot be aligned.

SPIRV-Cross type-aliases the input struct pair to the local function pair to avoid a name conflict.

The problem was that the code above incorrectly attempts to aligned the set of structs that are used for local function variables, because they are type-aliased from the input set of structs.

The change on #464 passed all the regression tests...and some other tests I ran.

As @HansKristian-ARM requested...can we get a sample GLSL (not HLSL) shader that triggers this new issue, please? I'm asking for a GLSL shader so that we can include it in the SPRIV-Cross regression tests.

**Comment by HansKristian-ARM** [comment] 2018-02-22 19:28
For the record, it is also possible to use HLSL for regression tests, through assembly shaders.

Random idea on why it's failing: The "master" type of the type_alias is probably not a block type in this case ... The type alias system needs an overhaul, that much is clear.

**Comment by billhollings** [comment] 2018-02-22 19:36
Fair enough about HLSL...but GLSL is simpler to understand, and play with. So I would prefer a GLSL example...unless there is something stopping it from being available.

Yeah...I'm thinking that we may need to reinstate the code above...but put some additional storage or decoration tests around it to filter out those that don't need to be aligned.

It will be interesting to see how the SPIR-V from a sample shader submitted for this issue differs from that for the shader submitted for #457.

**Comment by HansKristian-ARM** [comment] 2018-02-22 19:39
I'm confident we'll figure it out at any rate :)

**Comment by fatkas** [comment] 2018-02-23 04:13
glsl source https://gist.github.com/fatkas/d3ea12425384726436d28857ee4863d6
old msl https://gist.github.com/fatkas/124ad624c8d6e49876fbf7dd1872a361
new msl https://gist.github.com/fatkas/7e0aac83c16e2a431898c490e4a116e5

**Comment by JJoosten** [comment] 2018-03-02 11:52
Hey everyone,

We are walking into the same issue. I have attached two glsl files that should have the same result; but due to wrong packing, produce very different results.

[working.glsl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1774916/working.glsl.txt)
[broken.glsl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1774917/broken.glsl.txt)
[working.mtl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1774918/working.mtl.txt)
[broken.mtl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/1774919/broken.mtl.txt)

On another note: @billhollings congrats with opening up the source for MoltenVK! :)

Cheers,

**Comment by JJoosten** [comment] 2018-03-02 17:01
Just some info that might help pinpoint the issue.
We found that the first access to the struct matters; thus updating the main of broken.glsl.txt with the following code, "solves" the issue. 

```	
void main()
{
    if(false)
        buf0[0].a;

    T1 v = buf0[0];
    float x = v.b;
    buf1[gl_GlobalInvocationID.x] = x;
}
```	
Moving the if statement under the T1 assignment, breaks the code again.

We found that in the case where it goes wrong; the function emit_struct_member, seems to be entered a type of TypeType of the struct instead of the TypeVariable of the struct.

Cheers,

**Comment by HansKristian-ARM** [comment] 2018-03-03 14:00
I think the main problem comes down to whether or not to emit the "clean" version of the struct, or the padded version of the struct. I fear we might need to emit both. Right now, we only emit one (probably the first one declared in the SPIR-V), so the statement order probably affects the result here.

@billhollings, have you had a chance to look at this yet? If not, I can have a look.

**Comment by JJoosten** [comment] 2018-03-06 11:48
#483 solved the issues for us! 

Cheers,

**Closed** 2018-03-06 15:41 UTC
Labels: bug
