### ISSUE TITLE
MSL: argument buffer resource location assignment issue with buffer and texture array

### ISSUE THREAD

**Issue by starbucksDave** [KhronosGroup/SPIRV-Cross#1171] opened 2019-10-10 22:40 UTC
When adding a buffer in the same set as a texture array when using argument buffers, the resource location assignment seems to fail.
```
program_source:17:53: error: cannot assign resource locations to 'spvDescriptorSet0'
kernel void main0(constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]])
                                                    ^
program_source:14:32: note: attribute 'id' set location to 0, but minimum is 1
    array<texture2d<float>, 5> bindings [[id(0)]];
```

GLSL
```
#version 460

layout(binding = 0, set = 0) buffer SomeBuffer { float data; };
layout(binding = 1, set = 0, rgba32f) uniform image2D bindings[5];

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main()
{
    for (int i = 0; i < 4; i++)
    {
        data += imageLoad(bindings[0 + i], ivec2(0, 0)).x;
    }
}
```

MSL
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SomeBuffer
{
    float data;
};

struct spvDescriptorSetBuffer0
{
    device SomeBuffer* m_22 [[id(0)]];
    array<texture2d<float>, 5> bindings [[id(0)]];
};

kernel void main0(constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]])
{
    for (int i = 0; i < 4; i++)
    {
        (*spvDescriptorSet0.m_22).data += spvDescriptorSet0.bindings[0 + i].read(uint2(int2(0))).x;
    }
}
```

Cheers,

**Comment by HansKristian-Work** [comment] 2019-10-11 08:47
I cannot reproduce this on master, using `./spirv-cross /tmp/test.spv --msl --msl-argument-buffers --msl-version 20000` I get:

```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SomeBuffer
{
    float data;
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1u);

struct spvDescriptorSetBuffer0
{
    device SomeBuffer* m_22 [[id(0)]];
    array<texture2d<float>, 5> bindings [[id(1)]];
};

kernel void main0(constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]])
{
    for (int i = 0; i < 4; i++)
    {
        (*spvDescriptorSet0.m_22).data += spvDescriptorSet0.bindings[0 + i].read(uint2(int2(0))).x;
    }
}
```
which looks fine to me.

**Comment by cdavis5e** [comment] 2019-10-11 23:08
What OS and what version of Metal?

**Comment by starbucksDave** [comment] 2019-10-13 20:49
@HansKristian-Work I will try to reproduce the problem using standalone SPIRV-Cross. 
It happened for me in MVK using Catalina and Metal 3 (@cdavis5e). I believe the msl version is 2.2.

**Comment by HansKristian-Work** [comment] 2019-10-14 10:02
If this happens in MVK, I suspect this is an MVK bug when assigning ids to resources. When you launch SPIRV-Cross standalone you get the automatic assignment path of resource IDs.

**Comment by HansKristian-Work** [comment] 2019-11-04 09:17
Closing, as there doesn't appear to be a SPIRV-Cross bug here.

**Closed by HansKristian-Work** 2019-11-04 09:17 UTC
Labels: not a bug, question
