### ISSUE TITLE
DecorationNonWritable is not respected

### ISSUE THREAD

**Issue by gwihlidal** [KhronosGroup/SPIRV-Cross#88] opened 2017-01-05 15:39 UTC
Compiler::parse has a comment which indicates that images are set to limited access, and then promoted up, but it doesn't seem like this is being handled properly:

"// glslangValidator does not emit required qualifiers here.
 // Solve this by making the image access as restricted as possible
 // and loosen up if we need to."

In the following example shader, inputTexture should be decorated as NonWriteable, but it is not. This makes reflecting the difference between DX-style SRVs vs UAVs quite challenging.

```
#version 430 core

precision highp float;
precision highp int;

layout (local_size_x = 1, local_size_y = 1) in;

layout(rgba16f) readonly uniform image2D inputTexture;
layout(r32f) writeonly uniform image2D outputTexture;

void main()
{
	ivec2 iId = ivec2(gl_GlobalInvocationID.xy) * 2;
	ivec2 oId = ivec2(gl_GlobalInvocationID.xy);
	ivec2 inputSize = imageSize(inputTexture);
	iId.x = clamp(iId.x, 0, max(0, inputSize.x - 2));
	iId.y = clamp(iId.y, 0, max(0, inputSize.y - 2));
	vec3 texel = 
		imageLoad(inputTexture, iId + ivec2(0, 0)).xyz +
		imageLoad(inputTexture, iId + ivec2(1, 0)).xyz +
		imageLoad(inputTexture, iId + ivec2(0, 1)).xyz +
		imageLoad(inputTexture, iId + ivec2(1, 1)).xyz;	
	imageStore(outputTexture, oId, vec4(dot(texel / 4.0, vec3(0.2126, 0.7152, 0.0722)), 0.0, 0.0, 0.0));
}
```

With SPIRV-Cross, I would expect the following to return true for inputTexture:
```
compiler.get_decoration(resource.id, spv::DecorationNonWritable)
```
With glslang::TIntermTraverser, the parsing is correct when visitSymbol is encountered. The following would result in layoutReadOnly being set to true:
```
virtual void visitSymbol(glslang::TIntermSymbol* base)
{
    if (base->getQualifier().storage == glslang::EvqUniform)
    {
        bool layoutReadOnly = base->getQualifier().readonly;
    }
}
```
Here is the disassembled spirv for the example shader (notice the correct OpDecorate %inputTexture NonWritable decoration):
```
; SPIR-V
; Version: 1.0
; Generator: Khronos Glslang Reference Front End; 1
; Bound: 100
; Schema: 0
               OpCapability Shader
               OpCapability ImageQuery
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main" %gl_GlobalInvocationID
               OpExecutionMode %main LocalSize 1 1 1
               OpSource GLSL 430
               OpName %main "main"
               OpName %iId "iId"
               OpName %gl_GlobalInvocationID "gl_GlobalInvocationID"
               OpName %oId "oId"
               OpName %inputSize "inputSize"
               OpName %inputTexture "inputTexture"
               OpName %texel "texel"
               OpName %outputTexture "outputTexture"
               OpDecorate %gl_GlobalInvocationID BuiltIn GlobalInvocationId
               OpDecorate %inputTexture DescriptorSet 0
               OpDecorate %inputTexture NonWritable
               OpDecorate %outputTexture DescriptorSet 0
               OpDecorate %outputTexture NonReadable
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
        %int = OpTypeInt 32 1
      %v2int = OpTypeVector %int 2
%_ptr_Function_v2int = OpTypePointer Function %v2int
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%gl_GlobalInvocationID = OpVariable %_ptr_Input_v3uint Input
     %v2uint = OpTypeVector %uint 2
         %18 = OpConstant %int 2
      %float = OpTypeFloat 32
         %27 = OpTypeImage %float 2D 0 0 0 2 Rgba16f
%_ptr_UniformConstant_27 = OpTypePointer UniformConstant %27
%inputTexture = OpVariable %_ptr_UniformConstant_27 UniformConstant
         %32 = OpConstant %uint 0
%_ptr_Function_int = OpTypePointer Function %int
         %36 = OpConstant %int 0
         %43 = OpConstant %uint 1
    %v3float = OpTypeVector %float 3
%_ptr_Function_v3float = OpTypePointer Function %v3float
         %57 = OpConstantComposite %v2int %36 %36
    %v4float = OpTypeVector %float 4
         %64 = OpConstant %int 1
         %65 = OpConstantComposite %v2int %64 %36
         %72 = OpConstantComposite %v2int %36 %64
         %79 = OpConstantComposite %v2int %64 %64
         %84 = OpTypeImage %float 2D 0 0 0 2 R32f
%_ptr_UniformConstant_84 = OpTypePointer UniformConstant %84
%outputTexture = OpVariable %_ptr_UniformConstant_84 UniformConstant
         %90 = OpConstant %float 4
         %93 = OpConstant %float 0.2126
         %94 = OpConstant %float 0.7152
         %95 = OpConstant %float 0.0722
         %96 = OpConstantComposite %v3float %93 %94 %95
         %98 = OpConstant %float 0
       %main = OpFunction %void None %3
          %5 = OpLabel
        %iId = OpVariable %_ptr_Function_v2int Function
        %oId = OpVariable %_ptr_Function_v2int Function
  %inputSize = OpVariable %_ptr_Function_v2int Function
      %texel = OpVariable %_ptr_Function_v3float Function
         %15 = OpLoad %v3uint %gl_GlobalInvocationID
         %16 = OpVectorShuffle %v2uint %15 %15 0 1
         %17 = OpBitcast %v2int %16
         %19 = OpCompositeConstruct %v2int %18 %18
         %20 = OpIMul %v2int %17 %19
               OpStore %iId %20
         %22 = OpLoad %v3uint %gl_GlobalInvocationID
         %23 = OpVectorShuffle %v2uint %22 %22 0 1
         %24 = OpBitcast %v2int %23
               OpStore %oId %24
         %30 = OpLoad %27 %inputTexture
         %31 = OpImageQuerySize %v2int %30
               OpStore %inputSize %31
         %34 = OpAccessChain %_ptr_Function_int %iId %32
         %35 = OpLoad %int %34
         %37 = OpAccessChain %_ptr_Function_int %inputSize %32
         %38 = OpLoad %int %37
         %39 = OpISub %int %38 %18
         %40 = OpExtInst %int %1 SMax %36 %39
         %41 = OpExtInst %int %1 SClamp %35 %36 %40
         %42 = OpAccessChain %_ptr_Function_int %iId %32
               OpStore %42 %41
         %44 = OpAccessChain %_ptr_Function_int %iId %43
         %45 = OpLoad %int %44
         %46 = OpAccessChain %_ptr_Function_int %inputSize %43
         %47 = OpLoad %int %46
         %48 = OpISub %int %47 %18
         %49 = OpExtInst %int %1 SMax %36 %48
         %50 = OpExtInst %int %1 SClamp %45 %36 %49
         %51 = OpAccessChain %_ptr_Function_int %iId %43
               OpStore %51 %50
         %55 = OpLoad %27 %inputTexture
         %56 = OpLoad %v2int %iId
         %58 = OpIAdd %v2int %56 %57
         %60 = OpImageRead %v4float %55 %58
         %61 = OpVectorShuffle %v3float %60 %60 0 1 2
         %62 = OpLoad %27 %inputTexture
         %63 = OpLoad %v2int %iId
         %66 = OpIAdd %v2int %63 %65
         %67 = OpImageRead %v4float %62 %66
         %68 = OpVectorShuffle %v3float %67 %67 0 1 2
         %69 = OpFAdd %v3float %61 %68
         %70 = OpLoad %27 %inputTexture
         %71 = OpLoad %v2int %iId
         %73 = OpIAdd %v2int %71 %72
         %74 = OpImageRead %v4float %70 %73
         %75 = OpVectorShuffle %v3float %74 %74 0 1 2
         %76 = OpFAdd %v3float %69 %75
         %77 = OpLoad %27 %inputTexture
         %78 = OpLoad %v2int %iId
         %80 = OpIAdd %v2int %78 %79
         %81 = OpImageRead %v4float %77 %80
         %82 = OpVectorShuffle %v3float %81 %81 0 1 2
         %83 = OpFAdd %v3float %76 %82
               OpStore %texel %83
         %87 = OpLoad %84 %outputTexture
         %88 = OpLoad %v2int %oId
         %89 = OpLoad %v3float %texel
         %91 = OpCompositeConstruct %v3float %90 %90 %90
         %92 = OpFDiv %v3float %89 %91
         %97 = OpDot %float %92 %96
         %99 = OpCompositeConstruct %v4float %97 %98 %98 %98
               OpImageWrite %87 %88 %99
               OpReturn
               OpFunctionEnd
```

Thank you!
Graham

**Comment by HansKristian-ARM** [comment] 2017-01-05 17:20
Hi. Yes, this bug is caused by an old workaround for glslang which is no longer relevant. I've submitted a PR which makes it more robust: https://github.com/KhronosGroup/SPIRV-Cross/pull/89. --dump-decoration now reports readonly/writeonly as well:

```
images
=============

 ID 029 : inputTexture (Set : 0) readonly
 ID 086 : outputTexture (Set : 0) writeonly
=============
```

**Comment by gwihlidal** [comment] 2017-01-05 19:23
Thanks for the fix :) I did find an additional issue that I had to track down with this. Manually masking the decoration_flags against DecorationNonWritable works (my example has 0x0000000401000000 & 0x0000000001000000), but Compiler::get_decoration incorrectly returns 0 (silently) for any of the boolean decorations like NonWritable, NonReadable, Coherent, Volatile, etc...

I propose something like the following:
https://github.com/gwihlidal/SPIRV-Cross/commit/862a71b4d3d4d21e19c75591578eb9d81f01f7dc

If you like it, I can add the other decorations as well to do the same thing and submit a PR.

Thanks,
Graham

**Comment by HansKristian-ARM** [comment] 2017-01-05 19:36
Oh ... ye, get_decoration wasn't supposed to be used with boolean values, but I guess it makes sense to allow it. I'd like a default case to return !!(flags & (1 << bit)) or something, same for get_member_decoration.

**Comment by HansKristian-ARM** [comment] 2017-01-05 22:08
Merged, thanks.

**Closed by HansKristian-ARM** 2017-01-05 22:08 UTC
