### ISSUE TITLE
Failure to generate GLSL from SPIR-V that decorates I/O block members with different buffers/strides

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/SPIRV-Cross#1573] opened 2020-12-24 05:50 UTC
I encountered this issue when implementing transform feedback support for I/O blocks in ANGLE, translating from OpenGL ES to Vulkan. In a test I wrote, I capture two members of the same I/O block with GL_SEPARATE_ATTRIBS. This means that each member of the I/O block would end up getting a different XfbBuffer and XfbStride decoration.

This ANGLE test passes with the GL backend of ANGLE (meaning that capturing members of the same I/O block with GL_SEPARATE_ATTRIBS works in multiple OpenGL implementations and each member is written to a different buffer). At the same time, ANGLE's translation to SPIR-V which decorates the members with different XfbBuffer and XfbStride passes on all Vulkan implementations we have access to.

However, SPIRV-Cross fails to generate GLSL from ANGLE's SPIR-V with this message:

```
SPIRV-Cross threw an exception: IO block member XfbStride mismatch.
```

There's a comment in the relevant piece of code in SPIRV-Cross:

```
// For blocks, there is a restriction where xfb_stride/xfb_buffer must only be declared on the block itself,
// since all members must match the same xfb_buffer. The only thing we will declare for members of the block
// is the xfb_offset.
```

Based on my experiments above, this restriction seems artificial (despite ARB_enhanced_layout agreeing with that comment), at least as far as SPIR-V is concerned.

---

Is there a bug here? Is this something that SPIR-V can express, but GLSL cannot formally? Could SPIRV-Cross output the mismatching xfb_buffer and xfb_stride layout qualifiers on the members anyway despite it being seemingly invalid GLSL? I believe that to be better than failing GLSL generation.

---

The relevant pieces of SPIR-V that ANGLE generates are:

```
               OpMemberDecorate %_uVSBlock 0 XfbBuffer 0
               OpMemberDecorate %_uVSBlock 0 XfbStride 4
               OpMemberDecorate %_uVSBlock 0 Offset 0
               OpMemberDecorate %_uVSBlock 1 XfbBuffer 1
               OpMemberDecorate %_uVSBlock 1 XfbStride 8
               OpMemberDecorate %_uVSBlock 1 Offset 0
               OpDecorate %_uVSBlock Block

  %_uVSBlock = OpTypeStruct %float %v2float
```

**Comment by HansKristian-Work** [comment] 2021-01-07 09:02
Willfully emitting broken GLSL is not a good idea, then I'd just get complaints about that instead. This seems like a weird mismatch, but glslangValidator does fail.

```
#version 450

out gl_PerVertex
{
	layout(xfb_buffer = 0, xfb_offset = 0, xfb_stride = 16) vec4 gl_Position;
	layout(xfb_buffer = 1, xfb_offset = 0, xfb_stride = 4) float gl_PointSize;
};

void main()
{
	gl_Position = vec4(1.0);
	gl_PointSize = 1.0;
}
```

```
ERROR: /tmp/test.vert:6: 'xfb_buffer' : member cannot contradict block (or what block inherited from global) 
ERROR: /tmp/test.vert:3: 'xfb_offset' : overlapping offsets at offset 0 in buffer 0
ERROR: /tmp/test.vert:3: 'xfb_stride' : all stride settings must match for xfb buffer 0
ERROR: 3 compilation errors.  No code generated.
```

This is also a SPIR-V restriction:

>  All block members in the output interface of the entry point being compiled that are in the same block and have a declared or inherited XfbBuffer decoration must specify the same XfbBuffer value.

What you can do instead is to strip the explicit Xfb decorations before cross compiling to GLSL and let the GL driver do automagic interleave etc, but not sure if that works in all cases, especially with explicit layout where you can have gaps in the capture buffers.

This SPIR-V violates specs, so closing as not a bug.

**Closed by HansKristian-Work** 2021-01-07 09:02 UTC
Labels: not a bug
