### ISSUE TITLE
Clean up obsolete CompilerMSL::MSLVertexAttr content?

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/SPIRV-Cross#1380] opened 2020-05-30 20:14 UTC
`MSLVertexAttr` contains 4 member variables that are obsolete legacy elements from early MoltenVK use, and are no longer referenced internally within SPIRV-Cross.

```
struct MSLVertexAttr
{
	uint32_t location = 0;
//	uint32_t msl_buffer = 0;
//	uint32_t msl_offset = 0;
//	uint32_t msl_stride = 0;
//	bool per_instance = false;
	MSLVertexFormat format = MSL_VERTEX_FORMAT_OTHER;
	spv::BuiltIn builtin = spv::BuiltInMax;
};
```

Would it make sense to remove them from the SPIRV-Cross C++ API?

**Comment by HansKristian-Work** [comment] 2020-06-02 14:24
Duplicate of https://github.com/KhronosGroup/SPIRV-Cross/issues/1050? Yes, I don't have any objection to removing them if they are unused. Need to stay around in C API though for ABI compatibility but should be considered deprecated.

**Closed** 2020-06-04 13:55 UTC
Labels: maintenance

**Comment by billhollings** [comment] 2020-06-04 14:08
Ha! My apologies for the self-duplicate issue! At least I'm consistent over time! 🤦🏻‍♂️

Thanks for taking care of it!
