### ISSUE TITLE
SelectionMerge / BranchConditional / Branch

### ISSUE THREAD

**Issue by Reveillios** [KhronosGroup/SPIRV-Cross#160] opened 2017-04-05 09:50 UTC
Hi,
I have been playing around with optimizing SPIR-V code and stumbled upon the following problem:

My SPIR-V:
```
					...
              11:    10(bool) ConstantFalse
              14:      6(int) Constant 2
              16:      6(int) Constant 1
					...
      20(result):     19(ptr) Variable Output
	      25:             TypePointer Function 6(int)
					...
         4(main):           2 Function None 3
               5:             Label
        28(temp):     25(ptr) Variable Function
                              SelectionMerge 31 None
                              BranchConditional 11 30 31
              30:               Label
                                Store 28(temp) 14
                                Branch 29
              31:             Label
                              Store 28(temp) 16
                              Branch 29
              29:             Label
              21:      6(int) Load 28(temp)
                              Store 20(result) 21
                              Return
                              FunctionEnd
```

SPIRV-Cross compiles this to:
```
out int result;
void main()
{
    int temp;
    if (true)
    {
        temp = 2;
        int _21 = temp;
        result = _21;
    }
    temp = 1;
    int _21 = temp;
    result = _21;
}
```

Note that the SPIR-V in Block 30 branches to Block 29 and NOT to Block 31. (This is valid as far as I know, please correct me if I am wrong)

So what I would expect: 
```
out int result;
void main()
{
    int temp;
    if (true)
    {
        temp = 2;
        int _21 = temp;
        result = _21;
	return;
    }
    temp = 1;
    int _21 = temp;
    result = _21;
}
```

cheers,
Reveillios

FYI: 
I am working with SPIR-V for my master's thesis and my setup looks like this:
GLSL ⇨ [glslang] ⇨ SPIR-V ⇨ [SPIRV-Tools(optimizer, validator)] ⇨ "opt SPIR-V" ⇨ [SPIRV-Cross] ⇨ GLSL

**Comment by HansKristian-ARM** [comment] 2017-04-05 10:03
This looks a bit odd ... Do you have the original .spv file?

**Comment by Reveillios** [comment] 2017-04-05 10:22
I attached the .spv
Note that I did an Inline Function Pass on the SPIRV module to get to this "odd" branch.


[test.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/895889/test.zip)

**Comment by HansKristian-ARM** [comment] 2017-04-05 10:37
Ok ... this is indeed a bit tricky.

The problem here is that block 30 is branching beyond the merge target of 31, so the code-gen will not think this "closes" the if bracket. It can't, because this is effectively a goto. :\

The equivalent codegen would have to be:
```
if (true)
{
    tmp = blah;
    goto %29
}
31:
   tmp = blah;
29:
  result = tmp;
  return;
```

We now get two independent streams which both will "inline" the code for block 29.

```
if (true)
{
    tmp = blah;

    // 29 is duplicated
    result = tmp;
    return;
}
   tmp = blah;
   // 29 is duplicated
  result = tmp;
  return;
```

The problem is that the final "return" is optimized away if the return block dominates the exit from the function, but here that's not quite right, because if anything can just branch into 29 at will it will be context-dependent when we can perform this redundant "return" removal.

**Comment by HansKristian-ARM** [comment] 2017-04-05 11:07
Meanwhile I think how to solve this properly, you can try this patch.

```
diff --git a/spirv_glsl.cpp b/spirv_glsl.cpp
index 7601028..58fce85 100644
--- a/spirv_glsl.cpp
+++ b/spirv_glsl.cpp
@@ -6892,8 +6892,9 @@ void CompilerGLSL::emit_block_chain(SPIRBlock &block)
                // we do not need an explicit return which looks out of place. Just end the function here.
                // In the very weird case of for(;;) { return; } executing return is unconditional,
                // but we actually need a return here ...
-               else if (!block_is_outside_flow_control_from_block(get<SPIRBlock>(current_function->entry_block), block) ||
-                        block.loop_dominator != SPIRBlock::NoDominator)
+               //else if (!block_is_outside_flow_control_from_block(get<SPIRBlock>(current_function->entry_block), block) ||
+               //         block.loop_dominator != SPIRBlock::NoDominator)
+               else
                        statement("return;");
                break;
 
```

**Comment by HansKristian-ARM** [comment] 2017-04-05 18:25
For reference, do you have the original GLSL file and .spv file you used to pass to spirv-opt?

**Comment by Reveillios** [comment] 2017-04-06 06:50
I attached all the files.
I used spirv-opt, but I implemented the inlining pass myself.

[input_ouput.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/901693/input_ouput.zip)

**Comment by HansKristian-ARM** [comment] 2017-04-26 07:27
This code has been declared illegal by the working group, so closing this as not a bug. It breaks structured control flow.

**Closed by HansKristian-ARM** 2017-04-26 07:27 UTC
