### ISSUE TITLE
Compiler::compile() Exception

### ISSUE THREAD

**Issue by FuXiii** [KhronosGroup/SPIRV-Cross#1911] opened 2022-04-11 03:27 UTC
the code:
1. first use glslang to parse GLSL string to Spir-V
2. use SpirV-Cross to parse Spir-V data to GLSL information
3. I want to see the GLSL source code from Compiler::compile()
4. then it breaken~
```CXX
    const char *esslVersion = glslang::GetEsslVersionString();
    std::cout << "esslVersion::" << esslVersion << std::endl;
    const char *glslVersion = glslang::GetGlslVersionString();
    std::cout << "glslVersion::" << glslVersion << std::endl;

    const char *shaderStr = "#version 400\n\
		#extension GL_ARB_separate_shader_objects : enable\n\
		#extension GL_ARB_shading_language_420pack : enable\n\
		layout(set=0, binding = 0) uniform buf {\n\
			mat4 mvp;\n\
		} ubuf;\n\
		layout(set=0, binding = 1) uniform buf1 {\n\
			mat4 mvp;\n\
		} ubuf1;\n\
		layout(set=2, binding = 0) uniform buf2 {\n\
			mat4 mvp;\n\
		} ubuf2;\n\
		layout(location = 0) in vec4 pos;\n\
		layout(location = 1) in vec2 inTexCoords;\n\
		layout(location = 0) out vec2 texcoord;\n\
		void main() {\n\
			texcoord = inTexCoords;\n\
			gl_Position = ubuf.mvp * pos;\n\
		}\0";
    bool isInitializeProcess = glslang::InitializeProcess();
    if (isInitializeProcess)
    {
        std::cout << "isInitializeProcess::Success" << std::endl;
    }
    else
    {
        std::cout << "isInitializeProcess::Failed" << std::endl;
    }
    EShLanguage stage = EShLanguage::EShLangVertex;
    glslang::TShader shader(stage);
    shader.setStrings(&shaderStr, 1);
    shader.setEnvInput(glslang::EShSource::EShSourceGlsl, stage, glslang::EShClient::EShClientVulkan, 100);
    shader.setEnvClient(glslang::EShClient::EShClientVulkan, glslang::EShTargetClientVersion::EShTargetVulkan_1_1);
    shader.setEnvTarget(glslang::EShTargetLanguage::EShTargetSpv, glslang::EShTargetLanguageVersion::EShTargetSpv_1_0);
    TBuiltInResource resources;
    {
        resources.maxLights = 32;
        resources.maxClipPlanes = 6;
        resources.maxTextureUnits = 32;
        resources.maxTextureCoords = 32;
        resources.maxVertexAttribs = 64;
        resources.maxVertexUniformComponents = 4096;
        resources.maxVaryingFloats = 64;
        resources.maxVertexTextureImageUnits = 32;
        resources.maxCombinedTextureImageUnits = 80;
        resources.maxTextureImageUnits = 32;
        resources.maxFragmentUniformComponents = 4096;
        resources.maxDrawBuffers = 32;
        resources.maxVertexUniformVectors = 128;
        resources.maxVaryingVectors = 8;
        resources.maxFragmentUniformVectors = 16;
        resources.maxVertexOutputVectors = 16;
        resources.maxFragmentInputVectors = 15;
        resources.minProgramTexelOffset = -8;
        resources.maxProgramTexelOffset = 7;
        resources.maxClipDistances = 8;
        resources.maxComputeWorkGroupCountX = 65535;
        resources.maxComputeWorkGroupCountY = 65535;
        resources.maxComputeWorkGroupCountZ = 65535;
        resources.maxComputeWorkGroupSizeX = 1024;
        resources.maxComputeWorkGroupSizeY = 1024;
        resources.maxComputeWorkGroupSizeZ = 64;
        resources.maxComputeUniformComponents = 1024;
        resources.maxComputeTextureImageUnits = 16;
        resources.maxComputeImageUniforms = 8;
        resources.maxComputeAtomicCounters = 8;
        resources.maxComputeAtomicCounterBuffers = 1;
        resources.maxVaryingComponents = 60;
        resources.maxVertexOutputComponents = 64;
        resources.maxGeometryInputComponents = 64;
        resources.maxGeometryOutputComponents = 128;
        resources.maxFragmentInputComponents = 128;
        resources.maxImageUnits = 8;
        resources.maxCombinedImageUnitsAndFragmentOutputs = 8;
        resources.maxCombinedShaderOutputResources = 8;
        resources.maxImageSamples = 0;
        resources.maxVertexImageUniforms = 0;
        resources.maxTessControlImageUniforms = 0;
        resources.maxTessEvaluationImageUniforms = 0;
        resources.maxGeometryImageUniforms = 0;
        resources.maxFragmentImageUniforms = 8;
        resources.maxCombinedImageUniforms = 8;
        resources.maxGeometryTextureImageUnits = 16;
        resources.maxGeometryOutputVertices = 256;
        resources.maxGeometryTotalOutputComponents = 1024;
        resources.maxGeometryUniformComponents = 1024;
        resources.maxGeometryVaryingComponents = 64;
        resources.maxTessControlInputComponents = 128;
        resources.maxTessControlOutputComponents = 128;
        resources.maxTessControlTextureImageUnits = 16;
        resources.maxTessControlUniformComponents = 1024;
        resources.maxTessControlTotalOutputComponents = 4096;
        resources.maxTessEvaluationInputComponents = 128;
        resources.maxTessEvaluationOutputComponents = 128;
        resources.maxTessEvaluationTextureImageUnits = 16;
        resources.maxTessEvaluationUniformComponents = 1024;
        resources.maxTessPatchComponents = 120;
        resources.maxPatchVertices = 32;
        resources.maxTessGenLevel = 64;
        resources.maxViewports = 16;
        resources.maxVertexAtomicCounters = 0;
        resources.maxTessControlAtomicCounters = 0;
        resources.maxTessEvaluationAtomicCounters = 0;
        resources.maxGeometryAtomicCounters = 0;
        resources.maxFragmentAtomicCounters = 8;
        resources.maxCombinedAtomicCounters = 8;
        resources.maxAtomicCounterBindings = 1;
        resources.maxVertexAtomicCounterBuffers = 0;
        resources.maxTessControlAtomicCounterBuffers = 0;
        resources.maxTessEvaluationAtomicCounterBuffers = 0;
        resources.maxGeometryAtomicCounterBuffers = 0;
        resources.maxFragmentAtomicCounterBuffers = 1;
        resources.maxCombinedAtomicCounterBuffers = 1;
        resources.maxAtomicCounterBufferSize = 16384;
        resources.maxTransformFeedbackBuffers = 4;
        resources.maxTransformFeedbackInterleavedComponents = 64;
        resources.maxCullDistances = 8;
        resources.maxCombinedClipAndCullDistances = 8;
        resources.maxSamples = 4;
        resources.maxMeshOutputVerticesNV = 256;
        resources.maxMeshOutputPrimitivesNV = 512;
        resources.maxMeshWorkGroupSizeX_NV = 32;
        resources.maxMeshWorkGroupSizeY_NV = 1;
        resources.maxMeshWorkGroupSizeZ_NV = 1;
        resources.maxTaskWorkGroupSizeX_NV = 32;
        resources.maxTaskWorkGroupSizeY_NV = 1;
        resources.maxTaskWorkGroupSizeZ_NV = 1;
        resources.maxMeshViewCountNV = 4;
        resources.limits.nonInductiveForLoops = 1;
        resources.limits.whileLoops = 1;
        resources.limits.doWhileLoops = 1;
        resources.limits.generalUniformIndexing = 1;
        resources.limits.generalAttributeMatrixVectorIndexing = 1;
        resources.limits.generalVaryingIndexing = 1;
        resources.limits.generalSamplerIndexing = 1;
        resources.limits.generalVariableIndexing = 1;
        resources.limits.generalConstantMatrixVectorIndexing = 1;
    }

    EShMessages messages = (EShMessages)(EShMsgSpvRules | EShMsgVulkanRules);
    if (!shader.parse(&resources, 100, false, messages))
    {
        std::cout << "Error::parse::something didn't work" << std::endl;
    }
    std::cout << "shader::parse::InfoLog::" << shader.getInfoLog() << std::endl;
    glslang::TProgram program;
    program.addShader(&shader);
    if (!program.link(messages))
    {
        std::cout << "Error::link::something didn't work" << std::endl;
    }
    std::cout << "program::link::InfoLog::" << program.getInfoLog() << std::endl;
    std::vector<uint32_t> spirv;
    glslang::GlslangToSpv(*(program.getIntermediate(stage)), spirv);

    std::cout << "Validate::Success" << std::endl;

    spirv_cross::CompilerGLSL glsl(spirv);

    spirv_cross::ShaderResources _resources = glsl.get_shader_resources();

    for (auto &resource : _resources.uniform_buffers)
    {
        const spirv_cross::SPIRType &type = glsl.get_type(resource.type_id);
        unsigned set = glsl.get_decoration(resource.id, spv::DecorationDescriptorSet);
        unsigned binding = glsl.get_decoration(resource.id, spv::DecorationBinding);

        printf("uniform_buffers %s at set = %u, binding = %u\n", resource.name.c_str(), set, binding);
    }

    std::string glslStr = glsl.compile();
    std::cout << "GLSL::Code::====================================================================\n" << std::endl;
    std::cout << glslStr << std::endl;
    std::cout << "====================================================================" << std::endl;

    glslang::FinalizeProcess();
```

before `std::string glslStr = glsl.compile()` the output:
```Cmd
esslVersion::OpenGL ES GLSL 3.20 glslang Khronos. 11.9.0
glslVersion::4.60 glslang Khronos. 11.9.0
isInitializeProcess::Success
shader::parse::InfoLog::
program::link::InfoLog::
Validate::Success
uniform_buffers buf at set = 0, binding = 0 
uniform_buffers buf1 at set = 0, binding = 1
uniform_buffers buf2 at set = 2, binding = 0
```

after I call `std::string glslStr = glsl.compile()`:
![image](https://user-images.githubusercontent.com/40132375/162660199-92f4dbf2-0805-4431-a06f-f43fef12c727.png)

And the Call Stack:
```CallStack
std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long() const (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\string:1456)
std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size() const (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\string:975)
bool std::__1::operator==<std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\string:4074)
std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const* std::__1::find<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (@std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const* std::__1::find<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&):13)
spirv_cross::CompilerGLSL::has_extension(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const (@spirv_cross::CompilerGLSL::has_extension(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const:18)
spirv_cross::CompilerGLSL::require_extension_internal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (@spirv_cross::CompilerGLSL::require_extension_internal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&):13)
spirv_cross::CompilerGLSL::find_static_extensions() (@spirv_cross::CompilerGLSL::find_static_extensions():635)
spirv_cross::CompilerGLSL::compile() (@spirv_cross::CompilerGLSL::compile():74)
```

**Comment by HansKristian-Work** [comment] 2022-04-12 15:42
Again related to https://github.com/KhronosGroup/SPIRV-Cross/issues/1912, LLVM MinGW is used. This is not actionable without further demonstration that there is a bug.

**Comment by HansKristian-Work** [comment] 2022-04-13 09:25
Closing as not a bug, resolved in other issue.

**Closed by HansKristian-Work** 2022-04-13 09:25 UTC
Labels: not a bug, needs triage
