### ISSUE TITLE
Compiletime type safety of SPIRV-Cross

### ISSUE THREAD

**Issue by Raikiri** [KhronosGroup/SPIRV-Cross#1093] opened 2019-07-21 12:09 UTC
While using this library, most of the time I spent was on struggling with its very widespread use of uint32_t for basically everything. In my opinion, it's unnecessarily easy to make a mistake like this:
```cpp
compiler.get_decoration(buffer.type_id, spv::DecorationDescriptorSet); //instead of .id
```
or this
```cpp
compiler.get_member_name(buffer.type_id, memberIndex); //instead of .base_type_id
```
or this
```cpp
compiler.get_type(buffer.id); //instead of .type_id
```
In this case, use of int-identifiers is equivalent to use of void* and opengl-like GLuint-for-everything approach both of which proved to be very prone to errors. However, majority of these mistakes could have been easily avoided by doing for example
```cpp
namespace spirv_cross
{
struct Id { uint32_t asInt; };
struct TypeId { uint32_t asInt;};
struct BaseTypeId {uint32_t asInt;};
namespace Resource
{
  Id id;
  TypeId type_id;
  BaseTypeId base_type_id;
}
//...
uint32_t Compiler::get_decoration(Id id, Decoration decoration) const {/**/}
//..
void main()
{
  Resource res = ...;
  compiler.get_decoration(res.type_id, spv::DecorationDescriptorSet); //compiletime error
  compiler.get_decoration(res.id, spv::DecorationDescriptorSet); //ok
}
}
```
or any other more appropriate way of providing a strongly typed variables that cannot be accidentally assigned to each other when they arent supposed to be.

**Comment by HansKristian-Work** [comment] 2019-07-21 15:12
Duplicate of https://github.com/KhronosGroup/SPIRV-Cross/issues/441.

This comes down to SPIR-V being based around flat uint32_t IDs being used for everything. It's been on the radar for a good while to make the C++ API be more type-safe in a similar fashion, but it never quite made the top of the pile of things to work on. This issue is more likely to get traction through external contribution.

It's not necessarily as simple as this, as it's possible that two or more types can use a function. It's perfectly acceptable for a type to have a decoration for example, as well as a variable. The alternative is to use typedefs to clarify intent, like the C API did.

While the uint32_t are not type safe in compile-time, the effective type is checked in runtime though, but that's not ideal, I agree.

**Comment by HansKristian-Work** [comment] 2019-09-05 10:02
Alright, picking this up now.

**Closed** 2019-09-06 12:22 UTC
Labels: duplicate, in progress, maintenance
