### ISSUE TITLE
SPIRVCross hangs on cfg.walk_from

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#226] opened 2017-07-21 11:18 UTC
I have a relatively complex shader that SPIRVCross seems to be having a lot of difficulty converting to glsl. Specifically this block of code is looping for a very long time.

```
cfg.walk_from(header_block.merge_block, [&](uint32_t walk_block) {
			// We found a block which accesses the variable outside the loop.
			if (blocks.find(walk_block) != end(blocks))
				static_loop_init = false;
		});
```

This is happening after I apply an inlining pass to the original SPIRV which was sourced from hlsl. If I pass unmodified SPIRV to SPIRVCross, it works. The root cause seems to be a big block of if/else statements that gets inlined into the main entry point, as I comment them out it seems to do a faster job of analyzing them. I don't have a minimal example that reproduces this behavior, but I'd like to send you the spv and readable spv to see if we can work through it (github won't let me attach the spv extension and I also don't want to put it here publicly if possible)

**Comment by redorav** [comment] 2017-07-21 17:55
As an update, disabling the cfg analysis makes it compile properly and works.

**Comment by HansKristian-ARM** [comment] 2017-07-24 07:02
That's bad. Can you upload the SPIR-V and if possible a way to generate that SPIR-V?

**Comment by redorav** [comment] 2017-07-24 09:26
Is there a way I can send you this privately? It's company code I'm trying to compile and I wouldn't like to link it here publicly.

**Comment by HansKristian-ARM** [comment] 2017-07-24 09:28
You can send it to hans-kristian.arntzen@arm.com.

**Comment by redorav** [comment] 2017-07-24 09:36
Done

**Comment by HansKristian-ARM** [comment] 2017-07-29 20:20
I'll close this as the failing shader after the fix was likely caused by SPIRV-Tools. Please open a new ticket if you find anything.

**Closed by HansKristian-ARM** 2017-07-29 20:20 UTC
Labels: bug
