### ISSUE TITLE
Wrong resource name in push constant buffers.

### ISSUE THREAD

**Issue by Cherser-s** [KhronosGroup/SPIRV-Cross#518] opened 2018-03-27 18:36 UTC
As far as I know, "name" field in "Resource" must contain the name of resource instead of the variable name.
For instance,
```glsl
layout (push_constant) uniform ColorBlock2{
    vec4 myColor;
} pConsts;
```
name must be "ColorBlock2", but the name field contains "pConsts". In case if variable name is not specified, field contains empty string.

**Comment by HansKristian-ARM** [comment] 2018-03-28 08:19
This is working as intended. Push constant blocks get translated into `uniform ColorBlock2 pConsts;` in GLSL, so what you care about is actually pConsts here, not the block name.

**Comment by Cherser-s** [comment] 2018-03-28 08:25
Hm, I thought that should work the same way as in uniform buffers, where the name field contains name of type instead of variable name.

**Comment by HansKristian-ARM** [comment] 2018-03-28 08:29
UBOs are translated as UBOs, but push constants become non-opaque "classic" uniforms in regular GLSL. In that case, it's the variable name which is significant.

**Comment by HansKristian-ARM** [comment] 2018-04-03 14:09
Closing this, as I think this has been resolved.

**Closed by HansKristian-ARM** 2018-04-03 14:09 UTC
Labels: question
