### ISSUE TITLE
zero length of dynamic arrays when at last offset in ubo/ssbo

### ISSUE THREAD

**Issue by ranlor** [KhronosGroup/SPIRV-Cross#1375] opened 2020-05-24 20:34 UTC
HI, I've noticed an issue when trying to get the array length 
when I try to get the array length of an dynamic array which is part of a ubo/ssbo, if that array is in the last position of the ubo/ssbo then the length is outputted in the reflection is zero.

for example , this simplified shader: 
```shader
#version 430

layout(set = 0, binding = 0) buffer ssboStruct {
    float variable_array[];
} ssboStructNamesapce;

void main()
{
    ssboStructNamesapce.variable_array[3] = 0.4f;
}
```

will result in the block size zero and the array length as zero, either  in json format reflection or using this code:

```cpp
for ( auto& ssbo : resources.storage_buffers)
{
   auto type = comp.get_type(ssbo.base_type_id);
   // struct size is zero
   size_t size = comp.get_declared_struct_size(type);
   // member size is zero 
   size_t member_size = comp.get_declared_struct_member_size(type, 0);
}
```
when I move the dynamic array from the last position in the buffer all the sizes get reported correctly:

```shader
#version 430

layout(set = 0, binding = 0) buffer ssboStruct {
    float variable_array[];
    float a;
} ssboStructNamesapce;

void main()
{
    ssboStructNamesapce.variable_array[3] = 0.4f;
}
```
Using the same code above (or using the json reflection format) this shader will result in a size of the struct as 20 bytes and the size of the "variable_array" as 16 bytes ( length 4 in json reflection ) as it is expected to be.

Am I missing something? Because the way it works now, the only way I have to get correct sizes is to pad the buffer with a scalar type

**Comment by cdavis5e** [comment] 2020-05-25 00:32
> Am I missing something? Because the way it works now, the only way I have to get correct sizes is to pad the buffer with a scalar type

In your first example, it's a runtime array `OpTypeRuntimeArray`. This does not have a defined size at compile time; its size is only known at run time, after the SSBO has been bound to the pipeline. So of course the size of the array and therefore of the struct is 0.

**Comment by HansKristian-Work** [comment] 2020-05-25 08:53
Indeed. SPIRV-Cross is correct here. Closing a not a bug.

```
layout(set = 0, binding = 0) buffer ssboStruct {
    float variable_array[];
    float a;
} ssboStructNamesapce;
```
is also invalid code. Runtime arrays can only occur as the last member of the block.

**Closed by HansKristian-Work** 2020-05-25 08:53 UTC
Labels: not a bug
