### ISSUE TITLE
spirv_cross::~Compiler destruction

### ISSUE THREAD

**Issue by FuXiii** [KhronosGroup/SPIRV-Cross#1912] opened 2022-04-12 15:33 UTC
I use glslang to generate spirv from glsl then use spirv_cross to parse,
the code:
```CXX
void Turbo::Core::TShader::InternalParseSpirV()
{
    std::vector<uint32_t> spirv;
    spirv.resize(this->size / sizeof(uint32_t));
    uint32_t *spirv_data = spirv.data();
    memcpy(spirv_data, this->code, this->size);

    spirv_cross::CompilerGLSL glsl(std::move(spirv));
    spirv_cross::ShaderResources resources = glsl.get_shader_resources();
}
```
the Call Stack:
```CallStack
RtlIsZeroMemory (@RtlIsZeroMemory:62)
RtlpNtSetValueKey (@RtlpNtSetValueKey:355)
RtlpNtSetValueKey (@RtlpNtSetValueKey:567)
RtlpNtSetValueKey (@RtlpNtSetValueKey:7391)
RtlGetCurrentServiceSessionId (@RtlGetCurrentServiceSessionId:1274)
RtlFreeHeap (@RtlFreeHeap:24)
free (@free:11)
void std::__1::__libcpp_operator_delete<void*>(void*) (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\new:245)
void std::__1::__do_deallocate_handle_size<>(void*, unsigned long long) (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\new:269)
std::__1::__libcpp_deallocate(void*, unsigned long long, unsigned long long) (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\new:279)
std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>*>::deallocate(std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>**, unsigned long long) (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\__memory\allocator.h:117)
std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>*> >::deallocate(std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>*>&, std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>**, unsigned long long) (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\__memory\allocator_traits.h:282)
std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>*> >::operator()(std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>**) (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\__hash_table:812)
std::__1::unique_ptr<std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>* [], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>*> > >::reset(std::nullptr_t) (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\__memory\unique_ptr.h:551)
std::__1::unique_ptr<std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>* [], std::__1::__bucket_list_deallocator<std::__1::allocator<std::__1::__hash_node_base<std::__1::__hash_node<spirv_cross::LocationComponentPair, void*>*>*> > >::~unique_ptr() (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\__memory\unique_ptr.h:495)
std::__1::__hash_table<spirv_cross::LocationComponentPair, spirv_cross::InternalHasher, std::__1::equal_to<spirv_cross::LocationComponentPair>, std::__1::allocator<spirv_cross::LocationComponentPair> >::~__hash_table() (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\__hash_table:1523)
std::__1::unordered_set<spirv_cross::LocationComponentPair, spirv_cross::InternalHasher, std::__1::equal_to<spirv_cross::LocationComponentPair>, std::__1::allocator<spirv_cross::LocationComponentPair> >::~unordered_set() (f:\llvm-mingw-20211002-msvcrt-x86_64\include\c++\v1\unordered_set:522)
spirv_cross::CompilerGLSL::~CompilerGLSL() (f:\VulkanSDK\1.3.204.1\Include\spirv_cross\spirv_glsl.hpp:73)
Turbo::Core::TShader::InternalParseSpirV() (e:\Turbo\engine\src\TShader.cpp:477)
```
![image](https://user-images.githubusercontent.com/40132375/162999199-e4eb78cd-eff6-4a7d-b214-0b181d9111ce.png)

**Comment by HansKristian-Work** [comment] 2022-04-12 15:40
I doubt this is actually a SPIRV-Cross bug. Was SPIRV-Cross and consumer built with exact same compiler and runtime? LLVM-MinGW seems like an esoteric setup that I do not know. A backtrace like this is not actionable unless there is concrete proof of where the SPIRV-Cross bug is. Do sanitizers say anything?

**Comment by FuXiii** [comment] 2022-04-13 02:54
What is sanitizers?

**Comment by FuXiii** [comment] 2022-04-13 03:08
I download spir-cross source project and the copy to my project `${project_path}/thirdparty/`,
the project files tree structure:
![image](https://user-images.githubusercontent.com/40132375/163092218-9dc10bcf-f4c2-4d0b-9d8c-15187e43c6ef.png)

the `CMakeLists.txt` is:
`${project_path}/CMakeLists.txt`:
```CMake
cmake_minimum_required(VERSION 3.0)

project(Turbo)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED true)

set(CMAKE_BUILD_TYPE "debug")

add_library(vulkan STATIC IMPORTED GLOBAL)
set_target_properties(vulkan PROPERTIES IMPORTED_LOCATION F:/VulkanSDK/1.3.204.1/Lib/vulkan-1.lib)

add_subdirectory(./thirdparty)

add_subdirectory(./engine)

aux_source_directory(./engine/src/ SRCS)

add_executable(${PROJECT_NAME} ./main.cpp ${SRCS})

target_include_directories(${PROJECT_NAME}
    PUBLIC ./engine/include
    )

target_link_directories(${PROJECT_NAME} 
PUBLIC thirdparty/VulkanMemoryAllocator/src
PUBLIC thirdparty/glslang/glslang
PUBLIC thirdparty/glslang/glslang/OSDependent

PUBLIC thirdparty/glslang/hlsl
PUBLIC thirdparty/glslang/OGLCompilersDLL
PUBLIC thirdparty/glslang/SPIRV

PUBLIC thirdparty/SPIRV-Cross
)

target_link_libraries(${PROJECT_NAME} PUBLIC 
vulkan
VulkanMemoryAllocator
glslang
OGLCompiler
OSDependent
SPIRV
spirv-cross-core
spirv-cross-glsl
spirv-cross-hlsl
)
```

`${project_path}/thirdparty/CMakeLists.txt`:
```CMake
add_subdirectory(./VulkanMemoryAllocator)
add_subdirectory(./glslang)
add_subdirectory(./SPIRV-Cross)
```

**Comment by FuXiii** [comment] 2022-04-13 04:17
I had fixed this problem, the reason is:
in `TShader.cpp` I write the include head file like this:
```CXX
#include <spirv_cross/spirv_glsl.hpp>
#include <spirv_cross/spirv_hlsl.hpp>
```
and the I try to find where is them?:
![image](https://user-images.githubusercontent.com/40132375/163098371-f3acf3e4-f516-447c-8d58-c93914164322.png)

I had include the spirv-cross head file in `Vulkan SDK` path

---

and then I fixed them to:
1. add the head files path in cmake
```CMake
target_include_directories(${PROJECT_NAME}
    PUBLIC ./engine/include
    PUBLIC ./thirdparty/SPIRV-Cross
    )
```
2. fix the head file:
```CXX
#include <spirv_glsl.hpp>
#include <spirv_hlsl.hpp>
```
where they are now in the spirv-cross scorce code project path:
![image](https://user-images.githubusercontent.com/40132375/163098819-bcc98172-0f97-4f97-b3f2-bdc56fac5b27.png)

and then everything going well, whatever the `~Compiler()` or `Compiler::compile()`

Hooray!!!
o(^▽^)o

**Comment by HansKristian-Work** [comment] 2022-04-13 09:25
Yes, likely what happened here was that calling code used mismatched headers with the .cpp implementation code, which will crash for sure. Closing as not a bug.

**Closed by HansKristian-Work** 2022-04-13 09:25 UTC
Labels: not a bug, question, needs triage
