### ISSUE TITLE
RWStructuredBuffer name miss important infomation

### ISSUE THREAD

**Issue by johnson3d** [KhronosGroup/SPIRV-Cross#1444] opened 2020-08-13 06:30 UTC
I defined a buffer like this:
RWStructuredBuffer<MeshCluster> ClusterArray : register(u2);
translate to GLSL like this:
layout(binding = 2, std430) buffer type_RWStructuredBuffer_MeshCluster
{
    MeshCluster _m0[];
} ClusterArray;

I find reflection by Name("ClusterArray") in d3d11. But I can't get name from gles, I just got "type_RWStructuredBuffer_MeshCluster"
Can you build the name as type_RWStructuredBuffer_MeshCluster_ClusterArray? Then I can split the name from it:P
thanks very much

**Comment by HansKristian-Work** [comment] 2020-08-13 19:07
You can reflect the instance name "ClusterArray" from the API explicitly by calling get_name on the `id` member of the resource. Or, you can always modify the type name before cross compilation if you want specific type names to be reflected in the source. Closing as not a bug.

**Closed by HansKristian-Work** 2020-08-13 19:07 UTC
Labels: not a bug

**Comment by johnson3d** [comment] 2020-08-14 23:53
Thank you,, But i try to get structuredbuffer name like this,but szName will be "buffer type_RWStructuredBuffer_MeshCluster", what's the api that name "ClusterArray"?

glGetProgramInterfaceiv(mProgram, GL_SHADER_STORAGE_BLOCK, GL_ACTIVE_RESOURCES, &storageBlockCount);
	for (GLint uIdx = 0; uIdx < storageBlockCount; uIdx++)
	{
		glGetProgramResourceName(mProgram, GL_SHADER_STORAGE_BLOCK, uIdx, 256, &length, szName);
