### ISSUE TITLE
2 uniform samplers are mapped to the same binding in GLSL output

### ISSUE THREAD

**Issue by Ihaa21** [KhronosGroup/SPIRV-Cross#1288] opened 2020-03-05 00:13 UTC
Hey, 

I just started using SPIRV-Cross and I have a shader that has 2 separate samplers (one for shadow and one for diffuse). The SPIRV has them at separate descriptor sets but they both have the same binding id inside the set. When the GLSL output is generated from the SPIRV binary, it has both samplers at binding 0 which shouldn't be the case since they are separate textures.

Below are the SPIRV files that I am generating GLSL for:

[forward_static_frag_vulkan.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/4290201/forward_static_frag_vulkan.zip)
[forward_static_frag_vulkan.spv.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/4290198/forward_static_frag_vulkan.spv.txt)

Below is the generated SPIRV GLSL:

[forward_static_frag_opengl.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/4290204/forward_static_frag_opengl.txt)

The 2 samples that get mapped to the same binding are:

layout(binding = 0) uniform sampler2D ShadowSampler;
layout(binding = 0) uniform sampler2D DiffuseSampler;

Previously they where in 2 separate descriptor sets and so they wouldn't conflict like they do in the generated GLSL.

layout(set = 0, binding = 0) uniform sampler2D DiffuseSampler;
layout(set = 1, binding = 0) uniform sampler2D ShadowSampler;

Let me know if you need anything else!

**Comment by HansKristian-Work** [comment] 2020-03-05 09:43
The ZIP is corrupt and the text file seems to contain some random error messages unrelated to this issue.

This is completely expected though, SPIRV-Cross is only trying to adhere to the given SPIR-V as much as it can.

When normal GLSL is emitted, descriptor sets are omitted as GL does not support them. You need to ensure that the bindings do what you expect. You can use the reflection API to remap (set, binding) to linear bindings before you compile. Alternatively you can use the reflection API to strip away all binding decorations and bind the textures later in the GL API.

**Comment by HansKristian-Work** [comment] 2020-03-08 14:40
Closing as this is working as intended. SPIRV-Cross cannot know how you want to map (set, binding) to flat descriptors for GL, this is something you need to deal with yourself.

**Closed by HansKristian-Work** 2020-03-08 14:40 UTC
Labels: not a bug, question

**Comment by Ihaa21** [comment] 2020-03-10 15:33
Hey, sorry you where right. I thought that binding locations works like Vulkan and OpenGL uses those to set uniform locations but it seems like locations are a separate concpet on top of bindings, so I just have to query the code for the locations like its a regular GLSL program. Thanks, and thanks a bunch for this tool! Super useful :)
